// <auto-generated />
using CineVault.DataAccessLayer.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CineVault.DataAccessLayer.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20250322155716_Added_Imdb-Id_To_Person")]
    partial class Added_ImdbId_To_Person
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CineVault.ModelLayer.ModelMovie.Actor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Imdb_ID")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.HasKey("Id");

                    b.ToTable("Actors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Imdb_ID = 0,
                            Name = "Leonardo DiCaprio"
                        },
                        new
                        {
                            Id = 2,
                            Imdb_ID = 0,
                            Name = "Joseph Gordon-Levitt"
                        },
                        new
                        {
                            Id = 3,
                            Imdb_ID = 0,
                            Name = "Elliot Page"
                        },
                        new
                        {
                            Id = 4,
                            Imdb_ID = 0,
                            Name = "John Travolta"
                        },
                        new
                        {
                            Id = 5,
                            Imdb_ID = 0,
                            Name = "Samuel L. Jackson"
                        },
                        new
                        {
                            Id = 6,
                            Imdb_ID = 0,
                            Name = "Matthew McConaughey"
                        },
                        new
                        {
                            Id = 7,
                            Imdb_ID = 0,
                            Name = "Anne Hathaway"
                        },
                        new
                        {
                            Id = 8,
                            Imdb_ID = 0,
                            Name = "Kate Winslet"
                        },
                        new
                        {
                            Id = 9,
                            Imdb_ID = 0,
                            Name = "Quentin Tarantino"
                        });
                });

            modelBuilder.Entity("CineVault.ModelLayer.ModelMovie.Director", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Imdb_ID")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.HasKey("Id");

                    b.ToTable("Directors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Imdb_ID = 0,
                            Name = "Christopher Nolan"
                        },
                        new
                        {
                            Id = 2,
                            Imdb_ID = 0,
                            Name = "Quentin Tarantino"
                        },
                        new
                        {
                            Id = 3,
                            Imdb_ID = 0,
                            Name = "James Cameron"
                        },
                        new
                        {
                            Id = 4,
                            Imdb_ID = 0,
                            Name = "Robert Rodriguez"
                        },
                        new
                        {
                            Id = 5,
                            Imdb_ID = 0,
                            Name = "George Lucas"
                        });
                });

            modelBuilder.Entity("CineVault.ModelLayer.ModelMovie.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IMDBId")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<double?>("Score")
                        .HasColumnType("float");

                    b.Property<bool>("Seen")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "title");

                    b.Property<string>("Year")
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "release_date");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IMDBId = 0,
                            Score = 9.0,
                            Seen = true,
                            Title = "Inception",
                            Year = "2010"
                        },
                        new
                        {
                            Id = 2,
                            IMDBId = 0,
                            Score = 9.0,
                            Seen = false,
                            Title = "Pulp Fiction",
                            Year = "1994"
                        },
                        new
                        {
                            Id = 3,
                            IMDBId = 0,
                            Score = 8.5,
                            Seen = true,
                            Title = "Interstellar",
                            Year = "2014"
                        },
                        new
                        {
                            Id = 4,
                            IMDBId = 0,
                            Score = 8.0,
                            Seen = true,
                            Title = "Titanic",
                            Year = "1997"
                        },
                        new
                        {
                            Id = 5,
                            IMDBId = 0,
                            Score = 7.0,
                            Seen = false,
                            Title = "Sin City",
                            Year = "2005"
                        },
                        new
                        {
                            Id = 6,
                            IMDBId = 0,
                            Score = 7.5,
                            Seen = true,
                            Title = "Star Wars",
                            Year = "2005"
                        });
                });

            modelBuilder.Entity("CineVault.ModelLayer.ModelMovie.MovieActor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActorId")
                        .HasColumnType("int");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.HasIndex("MovieId");

                    b.ToTable("MovieActors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActorId = 1,
                            MovieId = 1
                        },
                        new
                        {
                            Id = 2,
                            ActorId = 2,
                            MovieId = 1
                        },
                        new
                        {
                            Id = 3,
                            ActorId = 3,
                            MovieId = 1
                        },
                        new
                        {
                            Id = 4,
                            ActorId = 4,
                            MovieId = 2
                        },
                        new
                        {
                            Id = 5,
                            ActorId = 5,
                            MovieId = 2
                        },
                        new
                        {
                            Id = 6,
                            ActorId = 9,
                            MovieId = 2
                        },
                        new
                        {
                            Id = 7,
                            ActorId = 6,
                            MovieId = 3
                        },
                        new
                        {
                            Id = 8,
                            ActorId = 7,
                            MovieId = 3
                        },
                        new
                        {
                            Id = 9,
                            ActorId = 1,
                            MovieId = 4
                        },
                        new
                        {
                            Id = 10,
                            ActorId = 8,
                            MovieId = 4
                        },
                        new
                        {
                            Id = 11,
                            ActorId = 9,
                            MovieId = 5
                        },
                        new
                        {
                            Id = 12,
                            ActorId = 5,
                            MovieId = 6
                        });
                });

            modelBuilder.Entity("CineVault.ModelLayer.ModelMovie.MovieDirector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DirectorId")
                        .HasColumnType("int");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DirectorId");

                    b.HasIndex("MovieId");

                    b.ToTable("MovieDirectors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DirectorId = 1,
                            MovieId = 1
                        },
                        new
                        {
                            Id = 2,
                            DirectorId = 2,
                            MovieId = 2
                        },
                        new
                        {
                            Id = 3,
                            DirectorId = 1,
                            MovieId = 3
                        },
                        new
                        {
                            Id = 4,
                            DirectorId = 3,
                            MovieId = 4
                        },
                        new
                        {
                            Id = 5,
                            DirectorId = 2,
                            MovieId = 5
                        },
                        new
                        {
                            Id = 6,
                            DirectorId = 4,
                            MovieId = 5
                        },
                        new
                        {
                            Id = 7,
                            DirectorId = 5,
                            MovieId = 6
                        });
                });

            modelBuilder.Entity("CineVault.ModelLayer.ModelMovie.MovieActor", b =>
                {
                    b.HasOne("CineVault.ModelLayer.ModelMovie.Actor", "Actor")
                        .WithMany("MovieActors")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CineVault.ModelLayer.ModelMovie.Movie", "Movie")
                        .WithMany("MovieActors")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("CineVault.ModelLayer.ModelMovie.MovieDirector", b =>
                {
                    b.HasOne("CineVault.ModelLayer.ModelMovie.Director", "Director")
                        .WithMany("MovieDirectors")
                        .HasForeignKey("DirectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CineVault.ModelLayer.ModelMovie.Movie", "movie")
                        .WithMany("MovieDirectors")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Director");

                    b.Navigation("movie");
                });

            modelBuilder.Entity("CineVault.ModelLayer.ModelMovie.Actor", b =>
                {
                    b.Navigation("MovieActors");
                });

            modelBuilder.Entity("CineVault.ModelLayer.ModelMovie.Director", b =>
                {
                    b.Navigation("MovieDirectors");
                });

            modelBuilder.Entity("CineVault.ModelLayer.ModelMovie.Movie", b =>
                {
                    b.Navigation("MovieActors");

                    b.Navigation("MovieDirectors");
                });
#pragma warning restore 612, 618
        }
    }
}
